"""
Build a subject-list file for the whole available local dataset.

This scans your data directory and writes a Python file containing:

stories = [
    {"name": ..., "subject": ..., "bold_file": ..., "events_file": ..., "transcript_file": ...},
    ...
]

It supports two common layouts:

1) Current project-style layout:
   data/lucy/sub-026_task-lucy_bold.nii.gz
   data/lucy/task-lucy_events.tsv
   data/lucy/lucy_transcript.txt

2) Recursive/BIDS-like layout:
   data/sub-026/func/sub-026_task-lucy_bold.nii.gz
   data/lucy/task-lucy_events.tsv
   data/lucy/lucy_transcript.txt

Run examples
------------
python build_subject_list.py
python build_subject_list.py --data-dir data --output experiment_subject_list_all.py
python build_subject_list.py --output experiment_subject_list.py
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path


DEFAULT_STORIES = ["lucy", "merlin", "notthefallintact"]


def find_first(candidates):
    for p in candidates:
        if p.exists():
            return p
    return None


def find_story_files(data_dir: Path, story: str):
    story_dir = data_dir / story

    transcript = find_first([
        story_dir / f"{story}_transcript.txt",
        story_dir / "transcript.txt",
    ])
    if transcript is None and story_dir.exists():
        matches = sorted(story_dir.glob("*transcript*.txt"))
        transcript = matches[0] if matches else None

    events = find_first([
        story_dir / f"task-{story}_events.tsv",
        story_dir / f"{story}_events.tsv",
    ])
    if events is None and story_dir.exists():
        matches = sorted(story_dir.glob("*events.tsv"))
        events = matches[0] if matches else None

    return transcript, events


def extract_subject_id(path: Path):
    m = re.search(r"(sub-[A-Za-z0-9]+)", str(path))
    if not m:
        return None
    return m.group(1)


def find_bold_files(data_dir: Path, story: str):
    patterns = [
        f"{story}/sub-*task-{story}*bold.nii.gz",
        f"{story}/sub-*task-{story}*bold*.nii.gz",
        f"**/sub-*/func/sub-*task-{story}*bold.nii.gz",
        f"**/sub-*/func/sub-*task-{story}*bold*.nii.gz",
        f"**/sub-*task-{story}*bold.nii.gz",
        f"**/sub-*task-{story}*bold*.nii.gz",
    ]

    files = []
    for pattern in patterns:
        files.extend(data_dir.glob(pattern))

    # de-duplicate and sort by subject ID/path
    files = sorted(set(files), key=lambda p: (extract_subject_id(p) or "", str(p)))
    return files


def make_relative_or_absolute(path: Path, base: Path):
    try:
        return str(path.relative_to(Path.cwd())).replace("\\", "/")
    except ValueError:
        try:
            return str(path.relative_to(base.parent)).replace("\\", "/")
        except ValueError:
            return str(path).replace("\\", "/")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default="data", help="Root data folder.")
    parser.add_argument("--stories", default=",".join(DEFAULT_STORIES),
                        help="Comma-separated story names.")
    parser.add_argument("--output", default="configs/stories_all.py",
                        help="Output Python module.")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    story_names = [s.strip() for s in args.stories.split(",") if s.strip()]

    all_rows = []
    warnings = []

    for story in story_names:
        transcript, events = find_story_files(data_dir, story)
        if transcript is None:
            warnings.append(f"[{story}] transcript not found.")
        if events is None:
            warnings.append(f"[{story}] events file not found.")

        bold_files = find_bold_files(data_dir, story)
        if not bold_files:
            warnings.append(f"[{story}] no BOLD files found.")

        for bold in bold_files:
            subject = extract_subject_id(bold)
            if subject is None:
                warnings.append(f"Could not extract subject ID from {bold}")
                continue

            if transcript is None or events is None:
                continue

            all_rows.append({
                "name": story,
                "subject": subject,
                "bold_file": make_relative_or_absolute(bold, data_dir),
                "events_file": make_relative_or_absolute(events, data_dir),
                "transcript_file": make_relative_or_absolute(transcript, data_dir),
            })

    output = Path(args.output)
    with open(output, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by build_subject_list.py\n\n")
        f.write("stories = ")
        f.write(json.dumps(all_rows, indent=4))
        f.write("\n")

    print(f"Saved {len(all_rows)} subject-story rows to {output}")

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(" -", w)

    counts = {}
    for row in all_rows:
        counts[row["name"]] = counts.get(row["name"], 0) + 1
    print("\nCounts by story:")
    for story, count in counts.items():
        print(f" - {story}: {count}")


if __name__ == "__main__":
    main()
