from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path

import numpy as np
import pandas as pd


def load_stories(path: str):
    spec = importlib.util.spec_from_file_location("stories_module", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return list(module.stories)


def summarize_confounds(confounds_file: str):
    df = pd.read_csv(confounds_file, sep="\t")

    fd = df["framewise_displacement"] if "framewise_displacement" in df.columns else pd.Series(np.nan, index=df.index)
    fd = fd.fillna(0.0).astype(float)

    dvars_col = None
    for candidate in ["std_dvars", "dvars"]:
        if candidate in df.columns:
            dvars_col = candidate
            break

    if dvars_col:
        dvars = df[dvars_col].fillna(0.0).astype(float)
    else:
        dvars = pd.Series(np.nan, index=df.index)

    return {
        "n_volumes": len(df),
        "mean_fd": float(fd.mean()),
        "median_fd": float(fd.median()),
        "max_fd": float(fd.max()),
        "pct_fd_gt_0_5": float((fd > 0.5).mean()),
        "pct_fd_gt_0_9": float((fd > 0.9).mean()),
        "mean_dvars": float(dvars.mean()) if not dvars.isna().all() else np.nan,
        "max_dvars": float(dvars.max()) if not dvars.isna().all() else np.nan,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--subject-list", default="configs/stories_all_fmriprep_confounds.py")
    parser.add_argument("--output", default="results/diagnostics/motion_qc_summary.csv")
    parser.add_argument("--filtered-output", default="configs/stories_all_fmriprep_confounds_motionfiltered.py")
    parser.add_argument("--max-mean-fd", type=float, default=0.30)
    parser.add_argument("--max-pct-fd-gt-0-5", type=float, default=0.20)
    args = parser.parse_args()

    stories = load_stories(args.subject_list)

    rows = []
    kept = []
    excluded = []

    for row in stories:
        conf = row.get("confounds_file")
        if not conf or not Path(conf).exists():
            qc = {
                "n_volumes": np.nan, "mean_fd": np.nan, "median_fd": np.nan,
                "max_fd": np.nan, "pct_fd_gt_0_5": np.nan, "pct_fd_gt_0_9": np.nan,
                "mean_dvars": np.nan, "max_dvars": np.nan,
            }
            keep = False
        else:
            qc = summarize_confounds(conf)
            keep = (
                qc["mean_fd"] <= args.max_mean_fd and
                qc["pct_fd_gt_0_5"] <= args.max_pct_fd_gt_0_5
            )

        out_row = {
            "story": row["name"],
            "subject": row["subject"],
            "bold_file": row["bold_file"],
            "confounds_file": conf,
            "keep_motion_qc": bool(keep),
            **qc,
        }
        rows.append(out_row)

        if keep:
            kept.append(row)
        else:
            excluded.append(f"{row['subject']} {row['name']}")

    df = pd.DataFrame(rows)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out, index=False)

    filtered = Path(args.filtered_output)
    filtered.parent.mkdir(parents=True, exist_ok=True)
    import json
    filtered.write_text(
        "# Auto-generated by scripts/motion_qc_from_confounds.py\n\n"
        "stories = " + json.dumps(kept, indent=4) + "\n",
        encoding="utf-8",
    )

    print(f"Saved motion QC: {out}")
    print(f"Saved motion-filtered config: {filtered}")
    print(f"Kept {len(kept)} / {len(stories)} rows")

    if excluded:
        ex_path = Path("results/diagnostics/motion_qc_excluded_rows.txt")
        ex_path.parent.mkdir(parents=True, exist_ok=True)
        ex_path.write_text("\n".join(excluded) + "\n", encoding="utf-8")
        print(f"Excluded {len(excluded)} rows. See {ex_path}")

    if not df.empty:
        print("\nMotion QC summary:")
        print(df[["mean_fd", "max_fd", "pct_fd_gt_0_5", "pct_fd_gt_0_9"]].describe())


if __name__ == "__main__":
    main()
